version: '3.2'
services:
  gobarber-api:
    container_name: gobarber-api
    image: gobarber-api-0.0.1:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
     - "8080:8080"
    environment:
     - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
     - "gobarber-db"
  gobarber-db:
    container_name: gobarber-db
    image: postgres:11
    ports:
     - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobarber
